/**
 * ローカルmarket.db → 本番D1投入用SQLを生成（docs/11 §1 のTODO）。
 *   pnpm exec tsx src/cli/export-d1-seed.ts [--days 900] > seed.sql
 * 実行: cd ../worker && wrangler d1 execute okina --remote --file=../backtest/seed.sql
 */
import { openDb } from "../db.js";

const daysArg = process.argv.indexOf("--days");
const days = daysArg >= 0 ? Number(process.argv[daysArg + 1]) : 900;
const from = new Date(Date.now() - days * 86400000).toISOString().slice(0, 10);

const db = openDb();
const rows = db
  .prepare(
    `SELECT symbol, date, open, high, low, close, adj_close, volume
     FROM prices WHERE date >= ? ORDER BY symbol, date`,
  )
  .all(from) as {
  symbol: string;
  date: string;
  open: number;
  high: number;
  low: number;
  close: number;
  adj_close: number;
  volume: number;
}[];
db.close();

// D1のSQLファイル実行は複数文OK。UPSERTで冪等にし、500行ずつのマルチVALUESでサイズを抑える
console.log("-- generated by export-d1-seed.ts; idempotent upsert");
for (let i = 0; i < rows.length; i += 500) {
  const chunk = rows.slice(i, i + 500);
  const values = chunk
    .map(
      (r) =>
        `('${r.symbol}','${r.date}',${r.open},${r.high},${r.low},${r.close},${r.adj_close},${r.volume})`,
    )
    .join(",\n");
  console.log(
    `INSERT INTO prices (symbol, date, open, high, low, close, adj_close, volume) VALUES\n${values}\nON CONFLICT (symbol, date) DO UPDATE SET adj_close=excluded.adj_close, close=excluded.close, open=excluded.open, high=excluded.high, low=excluded.low, volume=excluded.volume;`,
  );
}
console.error(`generated: ${rows.length} rows since ${from}`);
